### ISSUE TITLE
Connection pool size lacks (obvious) control

### ISSUE THREAD

**Issue by savkov** [AYLIEN/aylien_newsapi_python#1]
Hi guys,

thanks for the great API. I'm experiencing a problem when trying to parallelise the request process. I get the following warning if I set the thread number to more than 4 and sometimes even with 4:

`urllib3.connectionpool WARNING  Connection pool is full, discarding connection: api.newsapi.aylien.com`

I looked into it and it seems that you are setting the `pool_size` parameter in `RESTClientObject` to 4 and then never actually exposing that to any of the other classes/parameters.

Is this on purpose, I know there are some restrictions on the number of hits per minute? What would be the best way to expose it? Is there an alternative? Is my use case totally wrong?

Lots of questions, I know, but I thought I should kickstart your issues page with a bang.

**Comment by iCEAGE** [comment]
Hi @savkov,

Thanks for opening an issue.

First of all, that's only a warning and that doesn't block you to create a new connection. It says only the connection pool is full.

https://urllib3.readthedocs.io/en/latest/advanced-usage.html
> By default, if a new request is made and there is no free connection in the pool then a new connection will be created. However, this connection will not be saved if more than maxsize connections exist.

Yes this is on purpose but in the next release we will increase the maxsize of the connection pool. I think exposing maxsize of connection pool would not be appropriate for such high level library.

When using concurrency, it might be good to use a callback function but that doesn't change the maxsize of pool connection and still you'll get the warning:

````python
def callback_function(api_response):
    print(api_response)

thread = api_instance.list_stories(callback=callback_function)
````

Please let me know if you have any questions.

**Comment by iCEAGE** [comment]
The latest version is using 20 as pool size now which I think it's enough for one client.
